### ISSUE TITLE
Moodle 1.9 as remote?

### ISSUE THREAD

**Issue by klorinczi** [cperves/moodle-block-my_external_backup_restore_courses#2]
Could be possible to use Moodle 1.9 as remote?

**Comment by cperves** [comment]
hello,
no you must have minimum version 3.0 and server and client must be with  same moodle version

**Comment by klorinczi** [comment]
How about using OK_Tech_Web_Services, which provides SOAP, REST under Moodle v1.9.x and Moodle 2.x?
https://docs.moodle.org/dev/Web_Services:OK_Tech_Web_Services#History

What do you think?

**Comment by cperves** [comment]
Seems to be an old article.
Moodle now has strong webservices that in my development I choose to use.
I implement webservices in order to make the two moodle comunicate to backup course and restore course.
That 's the reason why the two moodle needs to be in same version.
That fact is not required but strongly adviced since webservices use internal moodle method to bakup and restore courses and also backup/restore method of modules and blocks of courses may depend on their version.
