### ISSUE TITLE
Restore from different Moodle version

### ISSUE THREAD

**Issue by windhover15** [cperves/moodle-block-my_external_backup_restore_courses#9]
Dear Céline,

Is it really impossibel to restore courses from Moodle 3.9 to Moodle 4.1?
This summer we have to move a big (more then 20 000 courses) university Moodle from 3.9 to new clean 4.1 portal.
This plugin would be very useful (because we only need to copy about 5-6000 courses), but we can not upgrade the old server to 4.1 (the problem is the sofware environment) 
I created a test with the different Moodle versions and I get thit message is schedule task:
```
Execute scheduled task: Restore course from remote Moodles task (block_my_external_backup_restore_courses\task\backup_restore_task)
... started 22:30:02. Current memory use 20.4 MB.
Debugging increased temporarily due to faildelay of 86400
defaultcategoryid not defined for my_external_backup_restore_courses plugin, please correct this.
... used 2 dbqueries
... used 0.034055948257446 seconds
Scheduled task failed: Restore course from remote Moodles task (block_my_external_backup_restore_courses\task\backup_restore_task),error/user  not found
Backtrace:
* line 432 of /blocks/my_external_backup_restore_courses/locallib.php: call to block_my_external_backup_restore_courses_task_error_list->notify_errors()
* line 41 of /blocks/my_external_backup_restore_courses/classes/task/backup_restore_task.php: call to block_my_external_backup_restore_courses_task_helper::run_automated_backup_restore()
* line 263 of /lib/cronlib.php: call to block_my_external_backup_restore_courses\task\backup_restore_task->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 178 of /admin/cli/cron.php: call to cron_run()
```

**Is there any way to correct this problem?**
Thanks in advance!
Csaba

**Comment by cperves** [comment]
It is aboslutely not advised to restore from two differents Moodle version since this plugin use Moodle framework which changed beetween Moodle version,. Sometimes functions or classes are changing or missing, settings changed, deprecated methods and functions appeared triggering errors and this for each moodle plugins (core and others)

 I see in your error trace that it seems to come from the backup/restore plugin but even if corrected by applying 4.1 plugin new version class and functions on the 3.9 plugin version it will not garanty that the course will be correctly imported , making your new platform not sure at all

In our university we migrate old Moodle the same version of the new empty Moodle where we wan't to migrate courses
We make a copy of the old Moodle and then migrate it
if necessary due to php version for example we make it progressively
e.g : to pass from 3.9 to 4.1 we changed php to the version supported by both moodle 3.9 and moodle 4.1

**Comment by windhover15** [comment]
Thank you for your quick answer! :)
I will consider the upgrade option again. (php 7.4 may be the solution), or we return to the mass course copying we used before, which we solved with the help of Moosh.
Thanks again!
Csaba

**Comment by cperves** [comment]
Exactly : php 7.4 will enable you to migrate
